# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_2', '0002_auto_20160506_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=200, unique=1),
        ),
    ]
